version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/mydatabase
      AWS_ACCESS_KEY_ID: AKIAZQ3DOL52MZUDY5RQ
      AWS_SECRET_ACCESS_KEY: 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
      AWS_S3_BUCKET: chatbotplnflask
      AWS_S3_REGION: us-west-2
    networks:
      - mynetwork

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - mynetwork

volumes:
  mongo-data:

networks:
  mynetwork:
