version: '3.8'

services:
  app:
    build: .
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/mydatabase
      PORT: ${PORT}
    networks:
      - mynetwork

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - mynetwork

volumes:
  mongo-data:

networks:
  mynetwork:
